init: add configtest before starting

diff --git a/debian/init b/debian/init
--- a/debian/init
+++ b/debian/init
@@ -84,11 +84,16 @@ do_start()
     #   0 if daemon has been started
     #   1 if daemon was already running
     #   2 if daemon could not be started
+    #   3 if daemon configuration is not valid
     echo "Starting consul and backgrounding"
     start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid $USER --background --test -- $DAEMON_ARGS || return 1
     start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid $USER --background -- $DAEMON_ARGS || return 2
 
-    echo -n "Waiting for consul daemon to start and elect a leader..."
+    if ! "$DAEMON" configtest -config-dir "$CONFIG_DIR"; then
+        echo "FAIL: invalid configuration file"
+        return 3
+    fi
+    echo "Waiting for consul daemon to start and elect a leader..."
     started=0
     for i in `seq 1 30`; do
         if start-stop-daemon --quiet --stop --test --pidfile $PIDFILE --exec $DAEMON --user $USER; then
